clc
% Formulate prior

t_max = 1000;
[xt,yt] = generateData(t_max, gamrnd(3,2), normrnd(0,0.00001)); % dim(xt) = 1x(t_max+1)

% To begin with, we set the prior to a normal distribution, generated by taking the mu and
% sigma from 1000 datapoints.

pd = fitdist(xt,'Normal');
prior_mu = pd.mu;
prior_sigma = pd.sigma;

% Step 1, t = 0.
N = 200;
particles = normrnd(prior_mu, prior_sigma, N, 1); % 200x1
estimated_x = mean(particles); % scalar

diffs = particles - estimated_x;
P0 = diffs*diffs'; % 200x200
estimated_x_a = [estimated_x', 0, 0]';
%particles_a = [particles






